(comment) @comment
(keyword) @keyword
(point) @point
(point_bracket) @point
(crease) @line
(crease_bracket) @line
(instance) @instance
(number) @number
(operator) @operator
(punct) @punct
(flap_bracket) @punct
