(test
 (name test_num)
 (libraries beloch alcotest zarith unix))

(test
 (name test_geom)
 (libraries beloch alcotest zarith))

(test
 (name test_fold_state)
 (libraries beloch alcotest zarith unix))

(test
 (name test_parse)
 (libraries beloch alcotest str))

(test
 (name test_eval)
 (libraries beloch alcotest zarith str))

(test
 (name test_e2e)
 (libraries beloch alcotest yojson zarith str))

(test
 (name test_diagnostic)
 (libraries beloch alcotest str))

(test
 (name test_golden)
 (libraries beloch alcotest yojson zarith str)
 (deps (glob_files ../examples/*.bel) (glob_files golden/*.fold)))

(test
 (name test_qqbar)
 (libraries beloch alcotest zarith))

(test
 (name test_field_merge)
 (libraries beloch alcotest zarith))

(test
 (name test_layer_order)
 (libraries beloch alcotest zarith))
