(executable
 (name probe)
 (modules probe)
 (libraries beloch zarith unix))
(executable
 (name fieldbench)
 (modules fieldbench)
 (libraries beloch zarith unix))
(executable
 (name spike_diag)
 (modules spike_diag)
 (libraries beloch zarith unix))
(executable
 (name spike_pe)
 (modules spike_pe)
 (libraries beloch zarith unix))
(executable
 (name spike_ca)
 (modules spike_ca ca)
 (foreign_stubs
  (language c)
  (names ca_stubs))
 (link_flags
  (-cclib -lflint -cclib -lgmp -cclib -lmpfr))
 (libraries beloch zarith unix))
